name: CI/CD Portfolio Auto-Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login ke Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-portfolio:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-portfolio:latest

  deploy-to-aws:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Deploy ke EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H 47.129.98.137 >> ~/.ssh/known_hosts
          
          # Bagian yang SANGAT PENTING (Wajib ada SUDO)
          ssh -i ~/.ssh/key.pem ubuntu@47.129.98.137 "
            # Login dulu di server biar gak error pull (pakai sudo)
            echo '${{ secrets.DOCKER_PASSWORD }}' | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin &&
            
            # Tarik image terbaru (pakai sudo)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-portfolio:latest &&
            
            # Matikan portfolio lama & staging (pakai sudo)
            sudo docker stop portfolio-app || true &&
            sudo docker rm -f portfolio-app || true &&
            
            # Usir aplikasi staging atau apapun yang pakai port 80
            sudo fuser -k 80/tcp || true &&
            
            # Jalankan container baru di port 80 (pakai sudo)
            sudo docker run -d \
              --name portfolio-app \
              --restart always \
              -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/my-portfolio:latest
          "